### ISSUE TITLE
Reg tests failed on Ubuntu 20.04 with Python 3.7+

### ISSUE THREAD

**Issue by friedenhe** [mdolab/dafoam#132]
The DASimpleTFoam reg tests failed when using Ubuntu 20.04 and Python 3.7+. The difference is very small though.

**Comment by shaheidula** [comment]
Dear Prof. Ping, 
I tried to install DAFoam on Ubuntu 20.04 and encounter the same problem here. May I ask if this problem is still not solved? 
Thanks

**Comment by friedenhe** [comment]
Nope, it is not solved yet... You can still do optimization with it though.

**Comment by friedenhe** [comment]
This issue has been fixed in v2.2.9
