### ISSUE TITLE
Rotor 37 preProcessing.sh Script issue

### ISSUE THREAD

**Issue by AlecVS** [mdolab/dafoam#171]
## Type of issue

Installation

## Description
Issue executing the preProcessing.sh script in rotor 37 tutorial. I have been able to previously generate this mesh and complete the Rotor 37 Compressor tutorial on a Windows system. I am now trying to do the same thing on a Ubuntu system but am running into an issue when I try to generate the mesh. I followed the DAFoam documentation instructions and am not sure how to resolve the issue

### Steps to reproduce issue
1. Using Docker version 19.03.15 I pulled dafoam/opt-packages:v2.2.8 and started the DAFoam Docker image
2. I tried running the ./preProcessing.sh command which resulted in a permission denied error
3. Running sudo ./preProcessing.sh resulted in the following error: "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"

### Current behavior

![Screenshot from 2021-09-16 13-23-43](https://user-images.githubusercontent.com/83614464/133659377-08cc81d3-f3e6-48ba-95bf-85bf0f5b1557.png)

### Expected behavior
Mesh generation

### Code version (if relevant)
**Python version:** …

**External dependencies:** …

**Internal packages:** …

**Comment by friedenhe** [comment]
Check this https://dafoam.github.io/mydoc_get_started_faq.html#why-i-keep-getting-a-permission-denied-error-when-using-the-dafoam-docker-image

**Comment by AlecVS** [comment]
I must have missed that documentation. Thank you very much!
