### ISSUE TITLE
Add writeSensMap capability to v3 runScript

### ISSUE THREAD

**Issue by albisb** [mdolab/dafoam#501]
## Description
"writeSensMap" flag from daoptions is not working for v3 runScript, but it works for v2.

### Steps to reproduce issue
1. Activate "writeSensMap" in a v3 script using runAdjoint mode for FFD design variable and no output file is generated
2. Now, doing the same in a v2 script creates a sensitivity field altogether with the rest of fields.

### Current behavior
The sensitivity map is not computed

### Expected behavior
A sensitivity map is computed and saved in the processor*/0.*1 directories

### Code versions

DAFoam v3.0.8

**Comment by friedenhe** [comment]
@albisb This has been fixed in this commit: https://github.com/mdolab/dafoam/commit/aa18fb4231b6ee5169e56fc27bcd44f1e33afb06
