### ISSUE TITLE
Unable to run the preProcessing.sh in the demo file.

### ISSUE THREAD

**Issue by Karthi019** [mdolab/dafoam#71]
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Other (please describe) - Local user to run DAFOAM

## Description
A description of the issue.
I am a local user in this Linux system (CentOS7) and I do not have administrator priviliges, while using OpenFOAM and DAFoam, 
As a localuser, when I run docker and when i try to run the Airfoil code given in the tutorial, the following error appears when running the preProcessing.sh script. 

"./preProcessing.sh: line 11: logMeshGeneration.txt: Permission denied
./preProcessing.sh: line 12: logMeshGeneration.txt: Permission denied
./preProcessing.sh: line 13: logMeshGeneration.txt: Permission denied
./preProcessing.sh: line 14: logMeshGeneration.txt: Permission denied
./preProcessing.sh: line 15: logMeshGeneration.txt: Permission denied
 "
and when the runScript.py is then run, it says :

"
Generating mesh.. Done!
cp: cannot create directory '0': Permission denied
"
Please tell me a way to fix this.

### Steps to reproduce issue
1. Download the tutorials and run the scripts as a local user in CentOS7

### Current behavior
LogOpt.txt not getting generated and the code doesnt seem to run.

### Expected behavior

Successful compilration and results in Paraview.

### Code version (if relevant)
**Python version:** …

**External dependencies:** …

**Internal packages:** …

**Comment by friedenhe** [comment]
Can you move this question to [Discussions](https://github.com/mdolab/dafoam/discussions)?

**Comment by Karthi019** [comment]
moved to discussions
